# Error messages for challenge platform smart contract
# Based on digital marketplace error patterns

DIFFERENT_SENDER: str = "Different sender"
WRONG_RECEIVER: str = "Wrong receiver"
UNAUTHORIZED: str = "Unauthorized"
INSUFFICIENT_STAKE: str = "Insufficient stake amount"
CHALLENGE_ALREADY_EXISTS: str = "Challenge already exists"
CHALLENGE_NOT_ACTIVE: str = "Challenge not active"
CHALLENGE_ENDED: str = "Challenge has ended"
CHALLENGE_FULL: str = "Challenge is full"
ALREADY_PARTICIPATING: str = "Already participating in challenge"
NOT_PARTICIPATING: str = "Not participating in challenge"
NOT_TIME_FOR_ELIMINATION: str = "Not time for weekly elimination"
INSUFFICIENT_PARTICIPANTS: str = "Insufficient participants for elimination"
CHALLENGE_STILL_ACTIVE: str = "Challenge is still active"
CHALLENGE_NOT_ENDED: str = "Challenge has not ended"
INVALID_TASK: str = "Invalid task"
TASK_ALREADY_COMPLETED: str = "Task already completed"
INVALID_HEALTH_DATA: str = "Invalid health data"
HEALTH_DATA_ALREADY_SUBMITTED: str = "Health data already submitted for this period"
INVALID_MESSAGE: str = "Invalid message content"
MESSAGE_TOO_LONG: str = "Message too long"
TASK_NOT_FOUND: str = "Task not found"
INVALID_DATA_TYPE: str = "Invalid health data type"
INSUFFICIENT_HEALTH_DATA: str = "Insufficient health data for task completion"
